# Generated by Django 4.0.5 on 2022-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactoinPurpose',
            new_name='transactionPurpose',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionAmount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='transactions',
            field=models.ManyToManyField(null=True, to='bank_account.transaction'),
        ),
    ]
