# Generated by Django 4.0.5 on 2022-06-25 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_rename_transactoinpurpose_transaction_transactionpurpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
