# Generated by Django 4.0.5 on 2022-06-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_transaction_transactiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='transactions',
            field=models.ManyToManyField(to='bank_account.transaction'),
        ),
    ]
