# Generated by Django 4.0.5 on 2022-06-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transactionDate',)},
        ),
    ]
