# Generated by Django 4.0.5 on 2022-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='accounts',
            field=models.ManyToManyField(to='bank_account.bankaccount'),
        ),
    ]
